site_name: django-gesha
site_description: JavaScript utilities for Django projects.
site_url: https://django-gesha.readthedocs.io/en/latest/
repo_url: https://github.com/ely-as/django-gesha
edit_uri: blob/main/docs/
theme:
  name: material
  palette:
    scheme: slate
    primary: gesha
    accent: amber
  features:
    - content.code.annotate
  logo: assets/logo.svg
  favicon: assets/favicon.svg
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - Settings: settings.md
  - Contributing: contributing.md
  - Changelog: changelog.md
extra_css:
  - stylesheets/extra.css
